openapi: 3.0.0
info:
  title: Logistics API
  description: API for managing orders
  version: 1.0.0
paths:
  /orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: A list of orders
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                quantity:
                  type: integer
      responses:
        '201':
          description: Order created successfully
